// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://saepfmuqeywmyhmjzgkr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNhZXBmbXVxZXl3bXlobWp6Z2tyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgzNDM0MDUsImV4cCI6MjA2MzkxOTQwNX0.qpZe9WRNNfneUbnok47oDdYbZJXsAxBL3eUVyD2Cx6E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);